# creates a cacheMatrix object
# x should be a square matrix()
# set() can be used to set the matrix
# get() can be used to get the matrix
# setInverse() can be used to set the inverse
# getInverse() can be used to get the inverse
makeCacheMatrix <- function(x = matrix()) {
 inv <- NULL
 set <- function(y) {
            x <<- y
            inv <<- NULL
    }
    get <- function() x
    setinverse <- function(inverse) inv <<- inverse
    getinverse <- function() inv
    
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)	
}

## Write a short comment describing this function

# cacheSolve takes a cacheMatrix object (generated by makeCacheMatrix), and solves for its inverse.
# It will check if the inverse is already solved, and if so retrieve it, otherwise it will solve and cache the result.
cacheSolve <- function(x, ...) {
  m <- x$getInverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setInverse(m)
  m
}

